-- MySQL Script generated by MySQL Workbench
-- Wed Nov 21 20:34:32 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema webservice_bank
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `webservice_bank` ;

-- -----------------------------------------------------
-- Schema webservice_bank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webservice_bank` DEFAULT CHARACTER SET utf8 ;
USE `webservice_bank` ;

-- -----------------------------------------------------
-- Table `webservice_bank`.`nasabah`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webservice_bank`.`nasabah` ;

CREATE TABLE IF NOT EXISTS `webservice_bank`.`nasabah` (
  `nama` VARCHAR(100) NULL,
  `nomor_kartu` INT NOT NULL,
  `saldo` INT NULL,
  PRIMARY KEY (`nomor_kartu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webservice_bank`.`transaksi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webservice_bank`.`transaksi` ;

CREATE TABLE IF NOT EXISTS `webservice_bank`.`transaksi` (
  `no_pengirim` INT NOT NULL,
  `no_penerima` INT NOT NULL,
  `jumlah` VARCHAR(45) NULL,
  `waktu_transaksi` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`waktu_transaksi`, `no_pengirim`, `no_penerima`),
  INDEX `fk_nomorkartu_idx` (`no_pengirim` ASC),
  INDEX `fk_nomor_kartu_penerima_idx` (`no_penerima` ASC),
  CONSTRAINT `fk_nomor_kartu_pengirim`
    FOREIGN KEY (`no_pengirim`)
    REFERENCES `webservice_bank`.`nasabah` (`nomor_kartu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nomor_kartu_penerima`
    FOREIGN KEY (`no_penerima`)
    REFERENCES `webservice_bank`.`nasabah` (`nomor_kartu`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
